version: '3.8'

        services:
          app:
            build: .
            ports:
              - "8081:8081"
            environment:
              - MONGODB_URI=mongodb://mongodb:27017/franchise-api-db
            depends_on:
              - mongodb
            restart: on-failure

          mongodb:
            image: mongo:7.0
            ports:
              - "27017:27017"
            volumes:
              - mongodb_data:/data/db
            restart: always

        volumes:
          mongodb_data: