version: '3.8'

services:
  franchise-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MONGODB_URI=mongodb://mongodb:27017/franchise-api-db
    depends_on:
      - mongodb
    networks:
      - franchise-network

  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=franchise-api-db
    volumes:
      - mongodb_data:/data/db
    networks:
      - franchise-network

networks:
  franchise-network:
    driver: bridge

volumes:
  mongodb_data: