services:
  - type: web
    name: franchise-api
    env: java
    plan: free
    buildCommand: mvn clean package -DskipTests
    startCommand: java -Xmx450m -Xms256m -server -jar target/*.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_TOOL_OPTIONS
        value: "-XX:MaxRAMPercentage=75.0 -XX:+UseContainerSupport"
    healthCheckPath: /actuator/health
    disk:
      name: franchise-api-disk
      mountPath: /tmp
      sizeGB: 1

databases:
  - name: franchise-mongodb
    databaseName: franchise_api_db
    user: franchiseuser
    plan: free