apiVersion: apps/v1
kind: Deployment
metadata:
  name: franchise-api
  labels:
    app: franchise-api
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: franchise-api
  template:
    metadata:
      labels:
        app: franchise-api
        version: v1
    spec:
      containers:
      - name: franchise-api
        image: ghcr.io/tu-usuario/franchise-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: franchise-api-secrets
              key: mongodb-uri
        - name: JAVA_OPTS
          value: "-Xmx1g -Xms512m -server -XX:+UseG1GC"
        
        # Resource limits and requests
        resources:
          limits:
            cpu: 1000m
            memory: 1.5Gi
          requests:
            cpu: 500m
            memory: 512Mi
        
        # Liveness probe
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        
        # Readiness probe
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        # Startup probe
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 10
      
      # Image pull secrets for private registry
      imagePullSecrets:
      - name: ghcr-secret
      
      # Security context
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000

---
apiVersion: v1
kind: Service
metadata:
  name: franchise-api-service
  labels:
    app: franchise-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: franchise-api

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: franchise-api-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - api.franchise.tu-dominio.com
    secretName: franchise-api-tls
  rules:
  - host: api.franchise.tu-dominio.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: franchise-api-service
            port:
              number: 80

---
apiVersion: v1
kind: Secret
metadata:
  name: franchise-api-secrets
type: Opaque
stringData:
  mongodb-uri: "mongodb+srv://user:password@cluster.mongodb.net/database?retryWrites=true&w=majority"

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: franchise-api-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: franchise-api

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: franchise-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: franchise-api
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
